node{

    stage('Cleaning'){
        removeOldBuilds()
    }
    stage('Building'){
       zip dir: '', glob: '', zipFile: 'hackidoo.zip'
    }
}

def removeOldBuilds(){
    def exists = fileExists: 'hackidoo.zip' 
    if(exists){
        sh 'rm hackidoo.zip'
    }
}