node{

    stage('Cleaning'){
        sh 'echo "removing old files"'
    }
    stage('Building'){
       zip dir: '', glob: '', zipFile: 'hackidoo.zip'
    }
}

def removeOldBuilds(){
    if( fileExists: 'hackidoo.zip'){
        sh 'rm hackidoo.zip'
    }
}